
postgresql:
  enabled: false

env:
  database: "off"

proxy:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${public_zone_cert}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"

dblessConfig:
  config: 
    _format_version: "1.1"

    services:
    - name: my-service
      url: https://httpbin.org
      routes:
      - name: my-route
        paths:
        - /
