
postgresql:
  enabled: false

env:
  database: "off"

proxy:
  type: ClusterIP
dblessConfig:
  config: 
    _format_version: "1.1"

    services:
    - name: my-service
      url: https://httpbin.org
      routes:
      - name: my-route
        paths:
        - /
